services:
  - type: web
    name: ultraguard-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ultraguard-db
          property: connectionString
    plan: free

databases:
  - name: ultraguard-db
    databaseName: ultraguard
    user: ultraguard_user
    plan: free 