services:
  - type: web
    name: ultraguard
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libpq-dev gcc python3-dev
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ultraguard-db
          property: connectionString
      - key: FLASK_ENV
        value: production

databases:
  - name: ultraguard-db
    databaseName: ultraguard
    user: ultraguard_user
    plan: free 